FROM  nginx:latest

# To build app & container image
# $ npm run build
# $ docker build -t us-central1-docker.pkg.dev/sample-firebase-ai-app-44ce8/meisi/my-app:v0 \
#   -f Dockerfile.static build/

COPY . /usr/share/nginx/html/

# COPY meisi.conf /etc/nginx/conf.d/default.conf

RUN sed -i '/index  index.html index.htm;/a \        try_files $uri /index.html;' /etc/nginx/conf.d/default.conf